-- Float rules
hl.window_rule({ match = { class = "^de\\.haeckerfelix\\.Shortwave$" },                   float = true })
hl.window_rule({ match = { class = "^Signal$" },                                          float = true })
hl.window_rule({ match = { class = "^com\\.github\\.rafostar\\.Clapper$" },               float = true })
hl.window_rule({ match = { class = "^app\\.drey\\.Warp$" },                               float = true })
hl.window_rule({ match = { class = "^net\\.davidotek\\.pupgui2$" },                       float = true })
hl.window_rule({ match = { class = "^yad$" },                                             float = true })
hl.window_rule({ match = { class = "^eog$" },                                             float = true })
hl.window_rule({ match = { class = "^io\\.github\\.alainm23\\.planify$" },                float = true })
hl.window_rule({ match = { class = "^io\\.gitlab\\.theevilskeleton\\.Upscaler$" },        float = true })
hl.window_rule({ match = { class = "^com\\.github\\.unrud\\.VideoDownloader$" },          float = true })
hl.window_rule({ match = { class = "^io\\.gitlab\\.adhami3310\\.Impression$" },           float = true })
hl.window_rule({ match = { class = "^io\\.missioncenter\\.MissionCenter$" },              float = true, size = "1290 950"})
hl.window_rule({ match = { class = "^org\\.pulseaudio\\.pavucontrol$" },                  float = true, size = "1221 619", })
hl.window_rule({ match = { title = "^File Operation Progress$" },                         float = true, size = "600 50", })
hl.window_rule({ match = { class = "^xfce-polkit$" },                                     float = true, size = "600 50", })
hl.window_rule({ match = { class = "^blueman-manager$" },                                 float = true, size = "600 300", })
hl.window_rule({ match = { title = "^Choose files to upload$" },                          float = true, size = "800 500", no_anim = true, no_shadow = true, border_size = 0, no_blur = true, center = 1, })
hl.window_rule({ match = { title = "^All Files$" },                                       float = true, size = "800 600", })
hl.window_rule({ match = { title = "^Affinity Photo 2$" },                                no_anim = true, no_shadow = true, border_size = 0, no_blur = true, no_dim = true, immediate = true, decorate = false, opaque = true, tonemap = off, })


hl.window_rule({ match = { class = "^[Ss]team$", title = "^Steam Settings$" }, float = true })
hl.window_rule({ match = { class = "^[Ss]team$", title = "^Friends List$" }, float = true })


-- Idle inhibit rules
hl.window_rule({ match = { class = "^(.*celluloid.*|.*mpv.*|.*vlc.*)$" },                                                                                            idle_inhibit = "fullscreen" })
hl.window_rule({ match = { class = "^.*[Ss]potify.*$" },                                                                                                             idle_inhibit = "fullscreen" })
hl.window_rule({ match = { class = "^(.*LibreWolf.*|.*floorp.*|.*brave-browser.*|.*firefox.*|.*chromium.*|.*zen.*|.*vivaldi.*)$" },                                  idle_inhibit = "fullscreen" })

-- Picture-in-picture
hl.window_rule({ match = { title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture).*$" }, tag = "picture-in-picture" })
hl.window_rule({ match = { tag = "picture-in-picture" }, float = true, pin = true, keep_aspect_ratio = true, move = "73% 72%", size = "25% 25%" })

-- Opacity rules
hl.window_rule({ match = { class = "^firefox$" },                                              opacity = 1.0 })
hl.window_rule({ match = { class = "^brave-browser$" },                                        opacity = 1.0 })
hl.window_rule({ match = { class = "^code-oss$" },                                             opacity = 1.0 })
hl.window_rule({ match = { class = "^[Cc]ode$" },                                              opacity = 1.0 })
hl.window_rule({ match = { class = "^code-url-handler$" },                                     opacity = 1.0 })
hl.window_rule({ match = { class = "^code-insiders-url-handler$" },                            opacity = 1.0 })
hl.window_rule({ match = { class = "^kitty$" },                                                opacity = 1.0 })
hl.window_rule({ match = { class = "^foot$" },                                                 opacity = 1.0 })
hl.window_rule({ match = { class = "^org\\.kde\\.dolphin$" },                                  opacity = 1.0 })
hl.window_rule({ match = { class = "^org\\.kde\\.ark$" },                                      opacity = 1.0 })
hl.window_rule({ match = { class = "^nwg-look$" },                                             opacity = 1.0 })
hl.window_rule({ match = { class = "^qt5ct$" },                                                opacity = 1.0 })
hl.window_rule({ match = { class = "^qt6ct$" },                                                opacity = 1.0 })
hl.window_rule({ match = { class = "^extsource$" },                                            opacity = 1.0 })
hl.window_rule({ match = { class = "^kvantummanager$" },                                       opacity = 1.0 })
hl.window_rule({ match = { class = "^org\\.pulseaudio\\.pavucontrol$" },                       opacity = 1.0 })
hl.window_rule({ match = { class = "^blueman-manager$" },                                      opacity = 1.0 })
hl.window_rule({ match = { class = "^nm-applet$" },                                            opacity = 1.0 })
hl.window_rule({ match = { class = "^nm-connection-editor$" },                                 opacity = 1.0 })
hl.window_rule({ match = { class = "^org\\.kde\\.polkit-kde-authentication-agent-1$" },        opacity = 1.0 })
hl.window_rule({ match = { class = "^polkit-gnome-authentication-agent-1$" },                  opacity = 1.0 })
hl.window_rule({ match = { class = "^org\\.freedesktop\\.impl\\.portal\\.desktop\\.gtk$" },    opacity = 1.0 })
hl.window_rule({ match = { class = "^org\\.freedesktop\\.impl\\.portal\\.desktop\\.hyprland$" }, opacity = 1.0 })
hl.window_rule({ match = { class = "^[Ss]team$" },                                             opacity = 1.0 })
hl.window_rule({ match = { class = "^steamwebhelper$" },                                       opacity = 1.0 })
hl.window_rule({ match = { class = "^[Ss]potify$" },                                           opacity = 1.0 })
hl.window_rule({ match = { initial_title = "^Spotify Free$" },                                 opacity = 1.0 })
hl.window_rule({ match = { initial_title = "^Spotify Premium$" },                              opacity = 1.0 })
hl.window_rule({ match = { class = "^com\\.github\\.rafostar\\.Clapper$" },                    opacity = 1.0 })
hl.window_rule({ match = { class = "^com\\.github\\.tchx84\\.Flatseal$" },                     opacity = 1.0 })
hl.window_rule({ match = { class = "^hu\\.kramo\\.Cartridges$" },                              opacity = 1.0 })
hl.window_rule({ match = { class = "^com\\.obsproject\\.Studio$" },                            opacity = 1.0 })
hl.window_rule({ match = { class = "^gnome-boxes$" },                                          opacity = 1.0 })
hl.window_rule({ match = { class = "^vesktop$" },                                              opacity = 1.0 })
hl.window_rule({ match = { class = "^discord$" },                                              opacity = 1.0 })
hl.window_rule({ match = { class = "^WebCord$" },                                              opacity = 1.0 })
hl.window_rule({ match = { class = "^ArmCord$" },                                              opacity = 1.0 })
hl.window_rule({ match = { class = "^app\\.drey\\.Warp$" },                                    opacity = 1.0 })
hl.window_rule({ match = { class = "^net\\.davidotek\\.pupgui2$" },                            opacity = 1.0 })
hl.window_rule({ match = { class = "^yad$" },                                                  opacity = 1.0 })
hl.window_rule({ match = { class = "^Signal$" },                                               opacity = 1.0 })
hl.window_rule({ match = { class = "^io\\.github\\.alainm23\\.planify$" },                     opacity = 1.0 })
hl.window_rule({ match = { class = "^io\\.gitlab\\.theevilskeleton\\.Upscaler$" },             opacity = 1.0 })
hl.window_rule({ match = { class = "^com\\.github\\.unrud\\.VideoDownloader$" },               opacity = 1.0 })
hl.window_rule({ match = { class = "^io\\.gitlab\\.adhami3310\\.Impression$" },                opacity = 1.0 })
hl.window_rule({ match = { class = "^io\\.missioncenter\\.MissionCenter$" },                   opacity = 1.0 })
hl.window_rule({ match = { class = "^io\\.github\\.flattool\\.Warehouse$" },                   opacity = 1.0 })

-- Misc rules
hl.window_rule({ match = { class = "^.*jetbrains.*$", title = "^win[0-9]+$" }, no_initial_focus = true })


-- Workspace and window rules examples

--hl.workspace_rule({ workspace = 1, monitor = "DP-1", })
--hl.workspace_rule({ workspace = 3, monitor = "DP-1", })
--hl.workspace_rule({ workspace = 5, monitor = "DP-1", })
--hl.workspace_rule({ workspace = 7, monitor = "DP-1", })
--hl.workspace_rule({ workspace = 2, monitor = "DP-2", })
--hl.workspace_rule({ workspace = 4, monitor = "DP-2", })
--hl.workspace_rule({ workspace = 6, monitor = "DP-2", })
--hl.workspace_rule({ workspace = 8, monitor = "DP-2", })

--hl.window_rule({ match = { initial_class = "^discord$" }, workspace = 2, })
--hl.window_rule({ match = { initial_class = "^org.jellyfin.JellyfinDesktop$" }, workspace = 8, })
--hl.window_rule({ match = { initial_class = "^steam$" }, workspace = 3, })
--hl.window_rule({ match = { initial_class = "^io.github.quodlibet.QuodLibet$" }, workspace = 6, })
--hl.window_rule({ match = { initial_class = "^org.signal.Signal" }, workspace = 4, })
